In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import  re
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
df=pd.read_csv('P:\AI-Resume-Screener\data\dataset_cleaned.csv')

In [42]:
df.head

<bound method NDFrame.head of                              Role  \
0           E-commerce Specialist
1                  Game Developer
2      Human Resources Specialist
3           E-commerce Specialist
4           E-commerce Specialist
...                           ...
10169             Product Manager
10170                 UI Engineer
10171                 UI Engineer
10172               Data Engineer
10173             Product Manager

                                              Transcript  \
0      Interviewer: Good morning, Jason. It's great t...
1      Interview Scene\n\nA conference room with a ta...
2      Interview Setting: A conference room in a medi...
3      Here's a simulated professional interview for ...
4      Here's the simulated interview:\n\nInterviewer...
...                                                  ...
10169  Here's a simulated interview for a Product Man...
10170  **Interviewer:** Hi Grace, thank you for comin...
10171  Here's a simulated interview for a UI Engineer...
10172  Here's a simulated interview for a Data Engine...
10173  Here's a simulated interview for a Product Man...

                                                  Resume decision  \
0      Here's a professional resume for Jason Jones:\...   reject
1      Here's a professional resume for Ann Marshall:...   select
2      Here's a professional resume for Patrick Mccla...   reject
3      Here's a professional resume for Patricia Gray...   select
4      Here's a professional resume for Amanda Gross:...   reject
...                                                  ...      ...
10169  Here's a sample resume for Diana Miller:\n\n**...   reject
10170  Here's a sample resume for Grace Taylor:\n\n**...   reject
10171  Here's a sample resume for Hank Brown:\n\n**Ha...   select
10172  Here's a sample resume for Diana Wilson:\n\n**...   reject
10173  Here's a sample resume for Charlie Miller, a P...   select

                                         Job_Description
0      Be part of a passionate team at the forefront ...
1      Help us build the next-generation products as ...
2      We need a Human Resources Specialist to enhanc...
3      Be part of a passionate team at the forefront ...
4      We are looking for an experienced E-commerce S...
...                                                  ...
10169  Here is a comprehensive job description for a ...
10170  Here is a sample job description for a UI Engi...
10171  Here is a job description for a UI Engineer ro...
10172  Here is a comprehensive job description for a ...
10173  Here is a comprehensive job description for a ...

[10174 rows x 5 columns]>

In [43]:
def cleanResume(resumeText):
    resumeText = re.sub('http\S+\s*', ' ', resumeText)  # remove URLs
    resumeText = re.sub('RT|cc', ' ', resumeText)  # remove RT and cc
    resumeText = re.sub('#\S+', '', resumeText)  # remove hashtags
    resumeText = re.sub('@\S+', '  ', resumeText)  # remove mentions
    resumeText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', resumeText)  # remove punctuations
    resumeText = re.sub(r'[^\x00-\x7f]',r' ', resumeText) 
    resumeText = re.sub('\s+', ' ', resumeText)  # remove extra whitespace
    return resumeText

In [44]:
df['Resume_cleaned'] = df['Resume'].apply(lambda x:cleanResume(x))
df['Job_Description_cleaned'] = df['Job_Description'].apply(lambda x:cleanResume(x))
df['Transcript_cleaned'] = df['Transcript'].apply(lambda x:cleanResume(x))
df.head()

,Role,Transcript,Resume,decision,Job_Description,Resume_cleaned,Job_Description_cleaned,Transcript_cleaned
0,E-commerce Specialist,"Interviewer: Good morning, Jason. It's great t...",Here's a professional resume for Jason Jones:\...,reject,Be part of a passionate team at the forefront ...,Here s a professional resume for Jason Jones J...,Be part of a passionate team at the forefront ...,Interviewer Good morning Jason It s great to m...
1,Game Developer,Interview Scene\n\nA conference room with a ta...,Here's a professional resume for Ann Marshall:...,select,Help us build the next-generation products as ...,Here s a professional resume for Ann Marshall ...,Help us build the next generation products as ...,Interview Scene A conference room with a table...
2,Human Resources Specialist,Interview Setting: A conference room in a medi...,Here's a professional resume for Patrick Mccla...,reject,We need a Human Resources Specialist to enhanc...,Here s a professional resume for Patrick M lai...,We need a Human Resources Specialist to enhanc...,Interview Setting A conference room in a mediu...
3,E-commerce Specialist,Here's a simulated professional interview for ...,Here's a professional resume for Patricia Gray...,select,Be part of a passionate team at the forefront ...,Here s a professional resume for Patricia Gray...,Be part of a passionate team at the forefront ...,Here s a simulated professional interview for ...
4,E-commerce Specialist,Here's the simulated interview:\n\nInterviewer...,Here's a professional resume for Amanda Gross:...,reject,We are looking for an experienced E-commerce S...,Here s a professional resume for Amanda Gross ...,We are looking for an experienced E commerce S...,Here s the simulated interview Interviewer Goo...

In [45]:
vectorizer = CountVectorizer(stop_words='english')
analyzer = vectorizer.build_analyzer()
df['Resume'] = df['Resume_cleaned'].apply(lambda x: ' '.join(analyzer(x)))
df['Job_Description'] = df['Job_Description_cleaned'].apply(lambda x: ' '.join(analyzer(x)))
df['Transcript'] = df['Transcript_cleaned'].apply(lambda x: ' '.join(analyzer(x)))
df.head()

,Role,Transcript,Resume,decision,Job_Description,Resume_cleaned,Job_Description_cleaned,Transcript_cleaned
0,E-commerce Specialist,interviewer good morning jason great meet welc...,professional resume jason jones jason jones co...,reject,passionate team forefront machine learning com...,Here s a professional resume for Jason Jones J...,Be part of a passionate team at the forefront ...,Interviewer Good morning Jason It s great to m...
1,Game Developer,interview scene conference room table chairs a...,professional resume ann marshall ann marshall ...,select,help build generation products game developer ...,Here s a professional resume for Ann Marshall ...,Help us build the next generation products as ...,Interview Scene A conference room with a table...
2,Human Resources Specialist,interview setting conference room medium sized...,professional resume patrick lain patrick lain ...,reject,need human resources specialist enhance team t...,Here s a professional resume for Patrick M lai...,We need a Human Resources Specialist to enhanc...,Interview Setting A conference room in a mediu...
3,E-commerce Specialist,simulated professional interview commerce spec...,professional resume patricia gray patricia gra...,select,passionate team forefront cloud computing comm...,Here s a professional resume for Patricia Gray...,Be part of a passionate team at the forefront ...,Here s a simulated professional interview for ...
4,E-commerce Specialist,simulated interview interviewer good morning a...,professional resume amanda gross amanda gross ...,reject,looking experienced commerce specialist join t...,Here s a professional resume for Amanda Gross ...,We are looking for an experienced E commerce S...,Here s the simulated interview Interviewer Goo...

In [46]:
df=df.drop(['Resume_cleaned','Job_Description_cleaned','Transcript_cleaned'],axis=1)

In [ ]:
word_vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000)
combined = pd.concat([
    df["Resume"],
    df["Job_Description"],
    df['Transcript']
])
word_vectorizer.fit(combined)
resume_vectorized=word_vectorizer.transform(df["Resume"])
job_description_vectorized=word_vectorizer.transform(df["Job_Description"])
transcript_vectorized=word_vectorizer.transform(df["Transcript"])

In [47]:
df.to_csv('P:\AI-Resume-Screener\data\dataset_cleaned.csv',index=False)